name: ridbuk
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">= 2.15.0-262.0.dev <3.0.0"

dependencies:
  avatar_glow: ^2.0.2
  cloud_firestore: ^1.0.4
  cupertino_icons: ^1.0.2
  dropdown_search: ^2.0.1
  firebase: ^9.0.2
  firebase_auth: ^3.3.9
  firebase_core: ^1.3.0

  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  get: 4.6.1
  image_picker: ^0.8.4+10
  intl: ^0.17.0
  nb_utils: ^4.4.12

dev_dependencies:
  flutter_lints: ^1.0.0
  firebase_storage: 10.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
